version: "3.9"

services:
  pulse-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4001
    depends_on:
      - pulse-backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  pulse-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/thynk_pulse
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thynk_pulse
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
