version: "3.9"

services:
  schooling-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4002
    depends_on:
      - schooling-backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  schooling-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4002:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/thynk_schooling
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thynk_schooling
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
